### ISSUE TITLE
Request: Pro Pedals help.

### ISSUE THREAD

**Issue by Dreams-Visions** [domdavis/ch-products-elite-map#6]
Warmest greetings. 

I've been using and loving your map since March, but I'm having a bit of trouble I was hoping you might be able to help me with. I just purchased the Pro Pedals with the goal of having a better feel when using Yaw in Elite to stay on top of targets with those fixed weapons. I'd like to accomplish this by setting my Yaw to either the pedal sliding front or back, or to the Right/Left break action of the pedals. 

I'm having a tough time figuring out where to make the necessary adjustments in the CM editor to preserve the existing pitch and roll while moving Yaw to the pedals. I've successfully been able to add my Pedals as JS3, but rotating it through the various axes only serves to introduce varying unintended results. I'm quite green to the CM editor but I think this will take me on the order of days to solve by myself. Having owned the Pro Pedals in the past, I was hoping you might be able to provide the scripting adjustment necessary to accomplish this task.

I greatly appreciate it if you would be able to help here.  I could get used to either the sliding of the pedals or the pressing of the pedals, but if you can advise on both so that I can go with the one that feels the most comfortable to me, I'll appreciate it. Thank you for your time and your map.

**Comment by domdavis** [comment]
I'll have a look tonight (not in front of my PC so can't check this), but you should be able to simple add the device as JS3, then change the axis for the two toe pedals to `none` for device and axis (there aren't enough spare axis for these and it can confuse things if you've got multiple devices configured). Finally change the yaw axis to be the first Direct X device in the list, and the last axis in the list (I think it's slider 1).

If you download that map and click on test/calibrate you should have a single device and yawing on the pedals should move one of the axis.

Fire up the game, go into the control config, find the yaw axis setting, click on it and just move the pedals. That should map that to yaw.

You'll now be able to yaw using buttons on the stick, and by moving the pedals.

If you want to use the toe pedals you'll need to set these up as buttons (historically when I used to have pedals I've use it for things like set throttle to 0, or boost, or reverse throttle). That can require some CMS scripting which I'll definitely need to be in front of my PC for.

**Comment by Dreams-Visions** [comment]
Thank you for your reply and time. I tried a few of these approaches and haven't had much luck just yet. I'll keep plugging away at it. If you have time to peek at it later, I'll appreciate it. Thanks again.

**Comment by domdavis** [comment]
OK, Fire up CM Manager:

* Load the Elite Map (I'm going to assume you're using the full map, but this works for the redux one too).
* Click the `Add` icon.
* Select _Pro Pedals_, these should appear as the third tab along. Select that tab.
* Click on the left brake on the image (or tap the left brake on the device)
* Confirm `DX Device` set to `none`, `DX Axis` set to `none`
* Click on the right brake on the image (or tap the right brake on the device)
* Confirm `DX Device` set to `none`, `DX Axis` set to `none`
* Click on the _Rudder Axis_ on the image (or move the rudder pedals)
* Select `CM Device 1` under `DX Device` and `Slider 1` under `DX Axis`
* Save the map (I'd suggest using a new name)
* Click `Download` on the toolbar
* Click `Test/Calibrate` on the toolbar
* Confirm there is only `Control Manager Device 1` in the list
* Click `Okay`
* Confirm moving the rudder pedals causes `S1` to move up and down

Launch _Elite: Dangerous_

* Select `Options` from the main menu
* Select `Controls`
* Scroll down to `Flight Rotation` and find `Yaw Axis`
* Click `[Joy U Axis]`
* Move the rudders, this should now change the value (although I'm not sure what to as I'm doing this blind)
* Click `Apply`
* Try one of the training missions to see if it's worked

Let me know how you get on. If it doesn't work then there's a couple of other things we can try. 

Few things to note. If you ever get an updated map from here you'll need to make these changes again. Also, this means that if you use the toggle in the map to swap the roll/yaw axis you'll actually just turn off the `X Axis` on your stick (yaw will still work on the pedals). This is because the `U Axis` is no longer mapped to anything. Hitting the toggle again will re-enable the `X Axis` as roll.

**Comment by domdavis** [comment]
Marking this as closed. If it's still and issue feel free to reopen it.

**Comment by mklinge** [comment]
Hi Dom, your mapping was a great base from which the setup my CH. I also have the pedals and after almost a year of Elite retirement I'm very happy you added these instructions. Thanks a lot.

**Comment by mklinge** [comment]
I think i was it fluke i had loading the mapping into the devices. It all seems to work exactly as by your extensive instructions. Thanks a lot. I never got the hang of using the scipt editor and used direct input and your map overview as a guide until i found your update how to add a pro pedals. You really made a lot of work on this. Thanks again.
